name             'course_database'
maintainer       'Edmund Haselwanter'
maintainer_email 'ehaselwanter@iteh.at'
license          'All rights reserved'
description      'Installs/Configures course_database'
long_description 'Installs/Configures course_database'
version          '0.1.1'

depends 'apt', '2.6.0'
depends 'mysql', '4.0.20'
depends 'database', '1.6.0'