name             'course_database'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures course_database'
long_description 'Installs/Configures course_database'
version          '0.1.1'

depends 'apt'
depends 'mysql', '~> 4.0.0'
depends 'database', '~> 1.6.0'